version: '1'

services:
  morpheus-chat:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    networks:
      - chat-network

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    networks:
      - chat-network


networks:
  chat-network:
    driver: bridge